export const INV_REASON = {
  RESERVATION_HOLD: "RESERVATION_HOLD",
  RESERVATION_RELEASE: "RESERVATION_RELEASE",
  SALE_COMMIT: "SALE_COMMIT",
  ORDER_CANCEL_RESTOCK: "ORDER_CANCEL_RESTOCK",
  RETURN: "RETURN",
  ADJUSTMENT: "ADJUSTMENT",
  DAMAGE: "DAMAGE",
  BULK_ADJUST: "BULK_ADJUST",
} as const;
